title: YANKEE MAJUMDER # your name (or website title) here
logo: "/images/ad.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Hello everyone, I am a Senior System Engineer with over 6 years of experience in IT, currently working at Cognizant.
  <br><br>
   Equiped with Deep Understanding of IAM and privilage access management.
   Experienced Senior System Engineer with a track record of architecting and deploying EUC solutions, 
   including VDI and application virtualization. 
   Proficient in troubleshooting complex EUC issues and skilled in technologies such as LDAP, Active Directory, and 
   Microsoft Endpoint Manager.
  <br><br>
  <a href="https://www.linkedin.com/in/yankee-majumder-6870ba134">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

